### ISSUE TITLE
Replace  `ramdisk/sbin/adbd`  witch current version

### ISSUE THREAD

**Issue by gxshao** [redispade/device_xiaomi_markw_twrp#1]
I was wondering can i just use current  `adbd` instead of my own 'ramdisk/sbin/adbd' in boot.img?

**Comment by redispade** [comment]
What do you mean ? Adbd is built from source on this tree

**Comment by gxshao** [comment]
> What do you mean ? Adbd is built from source on this tree

I thought it was an insecure `adbd`

**Comment by redispade** [comment]
It is insecure adbd from DT Flags. It is needed for adb backup --twrp from pc connection If you need it custom, you can get the code and change it according to your needs.

**Comment by gxshao** [comment]
> It is insecure adbd from DT Flags. It is needed for adb backup --twrp from pc connection If you need it custom, you can get the code and change it according to your needs.

i already done that.. but still unable to connect to my pc through ADB.. i am trying to build adbd in  android_6.0.1_r74 version now.... may i ask you which version at branch master?

**Comment by redispade** [comment]
This TWRP is built with branch PIE of Omnirom minimal manifest

**Comment by gxshao** [comment]
thx man
