### ISSUE TITLE
Repo manifest points to wrong github url

### ISSUE THREAD

**Issue by Laikar** [redispade/device_xiaomi_markw_twrp#2]
The omni_markw.xml manifest file ponts to [https://github.com/redispade/android_device_xiaomi_markw-twrp](https://github.com/redispade/android_device_xiaomi_markw-twrp), witch is a nonexisting repository,
changing it to point to this same repo apears to solve it, so i suggest changing it.

**Comment by redispade** [comment]
resolved 3dd2300
